### ISSUE TITLE
fail to build with wx 3.1.5

### ISSUE THREAD

**Issue by ildar** [pkulchenko/wxlua#98]
finally failing with:
```
[ 94%] Linking CXX executable ../../bin/Debug/wxLua
cd /usr/src/RPM/BUILD/wxlua-3.1.0.0/x86_64-alt-linux/apps/wxlua && /usr/bin/cmake -E cmake_link_script CMakeFiles/wxLua_app.dir/link.txt --verbose=1
/usr/bin/c++ -DLUA_COMPAT_MODULE  -Wall -fPIC -pthread -g -rdynamic CMakeFiles/wxLua_app.dir/wxlua.cpp.o -o ../../bin/Debug/wxLua  -Wl,-rpath,/usr/src/RPM/BUILD/wxlua-3.1.0.0/x86_64-alt-linux/lib/Debug: ../../lib/Debug/libwxlua_debugger-wxgtk3ud-3.1.0.0.so ../../lib/Debug/libwxlua_debug-wxgtk3ud-3.1.0.0.so /usr/lib64/liblua5.1.so -L/usr/lib64 -pthread -lwx_gtk3u_xrc-3.1 -lwx_baseu_xml-3.1 -lwx_gtk3u_stc-3.1 -lwx_gtk3u_gl-3.1 -lwx_gtk3u_html-3.1 -lwx_gtk3u_aui-3.1 -lwx_gtk3u_core-3.1 -lwx_baseu_net-3.1 -lwx_baseu-3.1 ../../lib/Debug/libwxlua_bind-wxgtk3ud-3.1.0.0.so ../../lib/Debug/libwxlua-wxgtk3ud-3.1.0.0.so /usr/lib64/liblua5.1.so -L/usr/lib64 -pthread -lwx_gtk3u_xrc-3.1 -lwx_baseu_xml-3.1 -lwx_gtk3u_stc-3.1 -lwx_gtk3u_gl-3.1 -lwx_gtk3u_html-3.1 -lwx_gtk3u_aui-3.1 -lwx_gtk3u_core-3.1 -lwx_baseu_net-3.1 -lwx_baseu-3.1 
ld: ../../lib/Debug/libwxlua_bind-wxgtk3ud-3.1.0.0.so: undefined reference to `wxPluralFormsCalculatorPtr::~wxPluralFormsCalculatorPtr()'
collect2: error: ld returned 1 exit status
```
full log: https://defuse.ca/b/s3nrYkPDiR48P4uMFJFLpL

P.S. BTW, chat has died with freenode scandal. I see no migration to Libre.chat. What would be the next chat platform? FYI Gitter has the great integration with Github.

**Comment by pkulchenko** [comment]
This is most likely a duplicate of #80. I'll probably turn that default off.

**Comment by pkulchenko** [comment]
@ildar, try the following patch to see if this fixes the issue:

```diff
diff --git a/wxLua/modules/wxbind/setup/wxluasetup.h b/wxLua/modules/wxbind/setup/wxluasetup.h
index 0c6292b..a5603b3 100644
--- a/wxLua/modules/wxbind/setup/wxluasetup.h
+++ b/wxLua/modules/wxbind/setup/wxluasetup.h
@@ -596,7 +596,7 @@
 #endif
 
 #ifndef wxLUA_USE_wxTranslations
-#define wxLUA_USE_wxTranslations                1
+#define wxLUA_USE_wxTranslations                0
 #endif
 
 #ifndef wxLUA_USE_wxTreebook
```

As explained in #80, it seems to be the issue with the packaging of wxwidgets in your host system, but I may just disable wxTranslations by default to help those users who may be running into this.

**Comment by ildar** [comment]
I am very sorry for the noise. I didn't do the mandatory search.
Duplicate, closing.
