### ISSUE TITLE
wxLuaBindLib failed to build with wxWidgeets 3.0.4.

### ISSUE THREAD

**Issue by ValeryKV** [pkulchenko/wxlua#39]
My env: Windows XP, VC 6.0, wxWidgets 3.0.4, wxLua 3.0.0.2 cmake 3.0.
Here is the error I get:

```
wxcore_gdi.cpp
Z:\3rdparty\wxLua-3.0\modules\wxbind\src\wxcore_gdi.cpp(6397) : error C2661: 'FindOrCreateFont' : no overloaded function takes 1 parameters
```

`FindOrCreateFont` with `const wxFontInfo& fontInfo` was added to wxWidgets 3.1.2 as inline
```
        { return FindOrCreateFont(fontInfo.GetPointSize(), fontInfo.GetFamily(),
                                  fontInfo.GetStyle(), fontInfo.GetWeight(),
                                  fontInfo.IsUnderlined(), fontInfo.GetFaceName(),
                                  fontInfo.GetEncoding()); }

```

**Comment by pkulchenko** [comment]
@ValeryKV, this should be fixed now. According to the wxwidgets interface files, it was introduced in 3.1.1, so I marked it as such in the API description.
